# This is a basic workflow to help you get started with Actions

name: Send Slack Parking Update

# Controls when the action will run.
on:
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Send_Update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Setup Java Sdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Check Status
        run: ./gradlew run -Pslack_webhook=${{ secrets.SLACK_WEBHOOK }}
